import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/layouts/Navigation";
import Footer from "@/components/layouts/Footer";
import AOSProvider from "@/components/providers/AOSProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className={"suppressHydrationWarning h-full antialiased"}>
      <body>
        <AOSProvider>{children}</AOSProvider>
      </body>
    </html>
  );
}
