import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/layouts/Navigation";
import Footer from "@/components/layouts/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className={`h-full antialiased`}>
      <body>
        
        {children}
        
      </body>
    </html>
  );
}
